### ISSUE TITLE
progressive enhancement for SEO

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#1]
Would be ideal to have the HTML of the entire thing in place for SEO purposes. 

Filters at the top would then filter things.

A cheap build process would be fine for this.

**Comment by paulirish** [comment]
The app is crazy simple and dying for a refactor.  requirements:

* data-binding
* templating
* serverside rendering

**Comment by ericguzman** [comment]
Any specific technologies in mind for these requirements, Paul?

**Comment by paulirish** [comment]
@ericguzman not really. 

I am comfortable with something using one or more of the following: web components / polymer 0.8 / ember (w fastboot) / react

**Comment by paulirish** [comment]
the refactor with polymer 1.0 has now been merged in #10 

we still don't ship the HTML, so going to leave the item open for now.

**Comment by kdzwinel** [comment]
I'm not sure how to approach that. Maybe we should have used [jekyll](http://jekyllrb.com/)* instead of polymer? Maybe there is a way to mix these two solutions?

* jekyll works nicely with github pages, and we could probably make it generate static pages based on protocol.json only
