### ISSUE TITLE
Protocol Browser - 404 on all resources

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#100]
Moved from: https://github.com/ChromeDevTools/devtools-protocol/issues/79  by @theduke

------

The browser currently shows only 404s for all resources, inlcuding head, stable1.2 and stable1.3:

https://chromedevtools.github.io/devtools-protocol/

Is there any other resource for how the protocol looks like?

**Comment by kdzwinel** [comment]
I can't reproduce it. Can you please let us know what browser you are using?

**Comment by theduke** [comment]
Chromium Version 63.0.3239.108 on Linux (Arch Linux).

**Comment by theduke** [comment]
I just tried with FF57 (also on Arch Linux), and there, I just get a whitescreen of death.

Console errors: 

```
TypeError: this.event.composedPath is not a function
[Learn More]
data:(function()%7B'use%20strict'%3Bconst%20a%3DElement.prototype%2Cb%3Da.matches%7C%7Ca.matchesSele:1:2138
TypeError: this.event.composedPath is not a function
[Learn More]
data:(function()%7B'use%20strict'%3Bconst%20a%3DElement.prototype%2Cb%3Da.matches%7C%7Ca.matchesSele:1:2228
TypeError: this._meta.byKey is not a function
[Learn More]
data:Polymer(%7Bis%3A'iron-icon'%2Cproperties%3A%7Bicon%3A%7Btype%3AString%7D%2Ctheme%3A%7Btype%3ASt:1:799
TypeError: p.shadowRoot is null
[Learn More]
devtools-protocol:4:1
```

**Comment by kdzwinel** [comment]
I still can't reproduce it (I've tried Chrome 65, Chromium 64 and FF57) :/

**Comment by theduke** [comment]
Meh, silly me. 

I had upgraded my kernel and not rebooted yet. All working fine now.

Can be closed.

**Comment by brycethomas** [comment]
FWIW the Chrome DevTools Protocol Viewer  page seems to have started 404'ing recently if you have the Vimium Chromium extension installed & enabled.  Disabling the Vimium extension fixed the issue for me.  I note that there's a quick flash of "Oops you hit a 404!" even when the page does load successfully (with Vimium disabled).  So presumably having Vimium enabled somehow causes the content layers that populate over the top of this to not get presented.

**Comment by JessieAMorris** [comment]
Thanks for the vimium comment, you just saved me a ton of time.

**Comment by matti** [comment]
404s on iphone/safari

**Comment by TimvdLippe** [comment]
This seems to be fixed, as I have Vimium installed and I can freely move around the website. Please let us know if you are still encountering issues.

**Comment by 0az** [comment]
@TimvdLippe I have reproduced this bug, or a variant, on Firefox Nightly 76.0a1 (2020-03-25). Could you reopen this issue

#### Steps to Reproduce
1. Clear all browser cache, etc.
2. Open the page.

#### Workaround
- Force a refresh with ctrl-shift-R.

---

I'm baffled, as FF DevTools network is reporting 404 for only the Favicon. Everything else is green. The only actual JS error is the same `p.shadowRoot` TypeError.

Tested this with/without addons too, and with a separate profile, on the off chance that UBO's block on GA affected things, or any of my other extensions. Still got the error.

**Comment by TimvdLippe** [comment]
I can see the 404 pop up temporarily, but can't reproduce said issue. However, I am planning on rewriting the loading behavior anyways, so likely that will fix it. If that rewrite doesn't fix the issue, please open a new issue for that.
