### ISSUE TITLE
Hash links on index.html don't work

### ISSUE THREAD

**Issue by eyqs** [ChromeDevTools/debugger-protocol-viewer#105]
For example, navigating to https://chromedevtools.github.io/devtools-protocol/#faq does not scroll down to the FAQ.

**Comment by paulirish** [comment]
True. I can reproduce.

Thanks for reporting.

fix up in #108

**Comment by paulirish** [comment]
fixed it in 3b222b950238c1ac1b9ce734c4e7cf8686183e75
