### ISSUE TITLE
Licensing of documentation and API names

### ISSUE THREAD

**Issue by adtrevor** [ChromeDevTools/debugger-protocol-viewer#119]
I would like to distribute a ChromeDevTools Protocol warper package, it would use same API naming and documentation as what's available in https://github.com/ChromeDevTools/debugger-protocol-viewer/tree/master/_data

Do I respect the license if I reference this project in `NOTICE`?

**Comment by paulirish** [comment]
@adtrevor 

1. sure, that's cool
2. you may want to use https://github.com/chromedevtools/devtools-protocol instead.
