### ISSUE TITLE
Data types missing

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#12]
We miss type information in the viewer. This makes it almost impossible to figure out how to use some methods e.g. `DOM.higlightNode` requires `higlightConfig` that has a very specific format (check it out [here](https://developer.chrome.com/devtools/docs/protocol/1.1/dom#type-HighlightConfig)).

Type information is available in the `protocol.json`, we are just not displaying it ATM.

**Comment by paulirish** [comment]
Nice. :) 

I just added type stuff in https://github.com/ChromeDevTools/debugger-protocol-viewer/commit/33d571845731c5af518616ce094d72c47216bce1   but i'd rather you do it your way because I feel pretty unsatisfied with my implementation.

I'm going to back out my types commit. You take this one.
