### ISSUE TITLE
Why are samples in a profile optional ?

### ISSUE THREAD

**Issue by agnivade** [ChromeDevTools/debugger-protocol-viewer#121]
This is a question rather than a bug. I hope this is the right place to ask. If not, please point me to it.

### What steps will reproduce the problem?

1. Go here https://chromedevtools.github.io/devtools-protocol/tot/Profiler#type-Profile
2. See the `samples` field. It is marked as an optional field.

From what I understand, a profile is a set of samples. And each sample has a set of function call sites (called as a node here ?). So how come `samples` is optional ? How can there be a profile without any samples ?

Also I am trying to figure out how to get the set of call sites in a sample. If I get the nodeID from the `samples` array, that just points to one node. Is it the `children` field then which contains the subsequent nodes ?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
