### ISSUE TITLE
[Question]: How can we grab Mouse events from Chrome Devtools Protocol API?

### ISSUE THREAD

**Issue by joychester** [ChromeDevTools/debugger-protocol-viewer#123]
This is a question rather than a bug report..

### What steps will reproduce the problem?

1. Under ChromeDevtools Performance tab, it can capture every detail mouse movement events under Interactions section, like following screenshots:
<img width="662" alt="Screen Shot 2019-12-11 at 16 32 27" src="https://user-images.githubusercontent.com/235618/70672385-edfe5780-1c33-11ea-901a-036ba92ded84.png">

### Question:
How can I get the Mouse events(Mouse Up/Down/scroll) detail info through Chrome Devtools Protocol API? Thanks!

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
