### ISSUE TITLE
How can I get the serial number of certificate in Network.securityDetails?

### ISSUE THREAD

**Issue by Febeoro** [ChromeDevTools/debugger-protocol-viewer#127]
### What steps will reproduce the problem?

1. When I get the driver log through this tool, I want to find the serial number of certificate in Network.securityDetails ;
2. However, I just get Null;
3. That's all.

### What is the expected result?
So I wonder if I got it wrong or if the feature is not yet open？

### What happens instead of that?
And if the feature is not yet open, when?

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
