### ISSUE TITLE
UI change - getting rid of <select>'s

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#13]
I've been using this viewer for some time and IMO method/event selectors are useless (while they add a significant amount of code to the project). It would be much better to remove them and have all metods/events folded by default (showing only names) with ability to expand them on click (to see description/parameters/etc.).

Also, the 'domain' menu could be changed to a flat list instead of a select.

What do you guys think?

**Comment by paulirish** [comment]
yeah agree.
i like the look of https://sample-solid.readme.io/v1.0/docs/orders-1

I figure…

* Domains available along the left side by default. 
* no visibility toggle for methods/events. 
* and URLs.

I wouldn't have an expand/contract on names, but that's me.
