### ISSUE TITLE
page.setDeviceOrientation is undefine

### ISSUE THREAD

**Issue by 298068845** [ChromeDevTools/debugger-protocol-viewer#153]
https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation/
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDeviceOrientationOverride
Can i use this api to set my deviceOrientation?

**Comment by paulirish** [comment]
as noted, `Page.setDeviceOrientationOverride` is deprecated.

https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation/#method-setDeviceOrientationOverride is the right choice.

**Comment by 298068845** [comment]
@paulirish how to get DeviceOrientation object to setDeviceOrientation?
I can't find a example for DeviceOrientation
