### ISSUE TITLE
Migrate to Lighthouse CI 0.4.0 🎉

### ISSUE THREAD

**Issue by patrickhulce** [ChromeDevTools/debugger-protocol-viewer#155]
Hi there! Friendly Lighthouse CI maintainer here 👋 Thanks for being an early adopter of LHCI and a heads up below on an infrastructure change that looks like it will affect you :)

**What's the problem? Please describe.**

Lighthouse CI 0.4.0 will be releasing soon. As part of the release process I will be upgrading `https://lhci-canary.herokuapp.com/`, which as the name implies, was meant to be the *canary* server for testing new releases. This repo is currently using this server, but I noticed the integration here uses the treo.sh GitHub CI action rather than LHCI directly which means it will break when this happens.

https://github.com/ChromeDevTools/debugger-protocol-viewer/blob/b01ea65add33bfcf84eb9bbbe301df68667ee501/.github/workflows/main.yml#L16-L27

**Describe the solution you'd like**

Two options, either are fine with me: 

1. Accept a PR that moves this repo's LHCI integration to use `@lhci/cli@next` so this repo can continue to use the canary server and assist with the release process by providing feedback.
2. Migrate off of `https://lhci-canary.herokuapp.com/` to a [self-hosted server](https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/heroku-server#setting-up-your-repo) (it's free 😃) if you'd prefer to stay on a stable version and upgrade at your own pace.

**Important Dates**

I am shooting to migrate the canary server to 0.4.0-beta.0 **tomorrow** and can have a PR ready for you by **10PM CDT tonight** if you'd like to stay on the canary managed server. If no action is taken before then, uploads to the LHCI server will start to fail. If this repo followed the official setup documentation for 0.3.x without using assertions, this should not start failing any CI builds and only result in log output, but your exact setup may differ.

**Comment by TimvdLippe** [comment]
I think we prefer option 1.
