### ISSUE TITLE
New design: Broken navigation when for some areas

### ISSUE THREAD

**Issue by auchenberg** [ChromeDevTools/debugger-protocol-viewer#18]
In the new (lovely) design, when you explore an area like "CSS" that has a relatively short string length, something weird happens with the navigation width. Looks like you are using flexbox +width:100% that might cause some funkyness.

![chrome debugger protocol viewer](https://cloud.githubusercontent.com/assets/173559/8447879/5bb3947e-1ffa-11e5-9dc2-073c83f36dc4.jpg)

**Comment by kdzwinel** [comment]
Hey Kenneth, thanks for reporting! The interesting thing is it only happens on Chrome stable - in Firefox and Chrome canary menu is always visible. For now I think I'll fix it with min-width, but I plan to replace whole menu with [material design menu element](https://elements.polymer-project.org/elements/paper-menu?view=demo:demo/index.html) anyway. Current design, as beautiful as it is, is only temporary :)

**Comment by paulirish** [comment]
thx for the report dude

**Comment by auchenberg** [comment]
Yeah, it looks like some flex-box funkyness I could quite figure out in 5min. Cool, Material sounds great!
