### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#2]
With a little time it could look much better. Any suggestions for a API reference style to be inspired from?

**Comment by kdzwinel** [comment]
JSDoc comes to mind, but it's not exactly beautiful - http://jsdoc.sourceforge.net/example/ .
I can create something simple based on http://getskeleton.com/ (same thing I used for EDL).

**Comment by paulirish** [comment]
https://stripe.com/docs/api is pretty attractive.

**Comment by auchenberg** [comment]
Github: https://developer.github.com/v3/gists/

Swagger: http://swagger.io/

**Comment by ericguzman** [comment]
+1 for Stripe's style.

The more I play with Swagger, the sweeter I think it is as a tool, but you have to start digging around to discover this. Stripe's API doc style + response samples laid out elegantly in the same view make it a more approachable style, IMO.

**Comment by paulirish** [comment]
Yup. http://readme.io/ came out recently to make the stripe style easy for everyone, but AFAICT, we can't just toss it a JSON and have it stay up to date. (@gkoberger can you confirm? - our docs is basically [this file](https://github.com/ChromeDevTools/debugger-protocol-viewer/blob/gh-pages/assets/protocol.js))

**Comment by gkoberger** [comment]
@paulirish yes and no!

We currently support a few specs (Swagger and APIDoc), and are super interested in adding more. Is the definition in any sort of existing format? Either way, we can probably write some sort of connector for it.

We'd love to help out! (And ReadMe would be free, too, since all this is open source :) )

**Comment by paulirish** [comment]
​I don't think it currently matches a API spec. Here it is:
https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/protocol.json

We currently display it like this
https://chromedevtools.github.io/debugger-protocol-viewer/ but we're ready
to explore other options.

Would an adapter for readme.io be much work?

**Comment by kdzwinel** [comment]
@paulirish Since polymer is in place, should we start using [material design elements](https://elements.polymer-project.org/browse?package=paper-elements)?

**Comment by paulirish** [comment]
Sure yah!
