### ISSUE TITLE
Menu text distorted after click

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#23]
Check what this is all about:

![text distorted](https://i.imgur.com/vu3UpJV.png)

and fix it.

**Comment by kdzwinel** [comment]
https://github.com/PolymerElements/paper-menu/issues/29

**Comment by bicknellr** [comment]
@kdzwinel Are you still able to repro this?

**Comment by kdzwinel** [comment]
No, thanks for checking.
