### ISSUE TITLE
Hide entries marked with "redirect".

### ISSUE THREAD

**Issue by dgozman** [ChromeDevTools/debugger-protocol-viewer#26]
Those are just for backwards compatibility, and we would like all implementations to switch to the new ones. For example, Page.getCookies should not be visible in favor of Network.getCookies.

**Comment by kdzwinel** [comment]
Thanks for reporting - I just fixed that (PR waiting for merge).

BTW how about entries marked with "hidden: true"? Should these be hidden to?

**Comment by dgozman** [comment]
Entries marked "hidden" are meant to change at any time. I'd mark non-hidden entries with "stable" sign or something.

**Comment by kdzwinel** [comment]
OK, I've crated a separate issue for that: https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/30
