### ISSUE TITLE
Mark non-hidden entries with "stable"

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#30]
@dgozman :
> Entries marked "hidden" are meant to change at any time. I'd mark non-hidden entries with "stable" sign or something.

**Comment by paulirish** [comment]
Good idea. That's a nice solution.

**Comment by kdzwinel** [comment]
It's super straightforward to do*, but I lack inspiration on how to present that message. Feel free to jump in!

* `{% if method.hidden == null or method.hidden == false %}` - same for event and type

**Comment by kdzwinel** [comment]
the flag is now called 'experimental'
