### ISSUE TITLE
protocol.json update script

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#33]
https://chromedevtools.github.io/debugger-protocol-viewer/CSS/ currently points to the DOM domain. That's because files in the `_domain` folder got out of sync with protocol.json after it was updated. These files have to be rebuilt every time `protocol.json` is updated (`node create-domain-files.js`).

We should have a script for updating `protocol.json` to avoid these kinds of manual errors. In the first step, script should download latest `protocol.json` (e.g. like this: https://github.com/cyrus-and/chrome-remote-interface/blob/master/Makefile#L7 ), in the second step domain files have to be rebuilt (`node create-domain-files.js`).

**Comment by paulirish** [comment]
Here's a better technique for pulling the json. (There's a better chance gittiles is up to date vs the svn mirror.)  @cyrus-and should do the same
```js
var url = 'https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/protocol.json?format=TEXT';
fetch(url).then( resp =>  resp.text().then( function(txt){  
    var protocol = atob(txt); 
    console.log(protocol);
}));
```

**Comment by paulirish** [comment]
yeah my mistake. forgot about the node thing.

20c28bd46382fd7985aecefc51ff30cb1604e09b updated the domain files to fix links
2c027ab58174228f69b47cd08709578d3e395c28 documented the state today.

That said, a script sounds ideal

**Comment by cyrus-and** [comment]
Got it, updated my script. Thanks @paulirish.

PS: Is there any news about [fetching the protocol directly from Chrome](/cyrus-and/chrome-remote-interface/issues/10)?

**Comment by kdzwinel** [comment]
we have `update-protocol-json.sh` for some time now. Closing this issue.
