### ISSUE TITLE
Search: highlight element when selected

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#36]
Sometimes, after we click on the search result, it's not immediately clear which section is the one that we search for.
Two scenarios I've identified:
- when there is no page reload user may miss that page jumped to the right section,
- when search result is at the very bottom of the page it won't be shown right under the header (where you would expect it to be).

**Comment by paulirish** [comment]
how about this: 
![image](https://cloud.githubusercontent.com/assets/39191/26569970/a5f1a316-44c2-11e7-995c-005a307edeb9.png)

**Comment by paulirish** [comment]
also do you remember how we do the #target scrolling without having the result be UNDER the fixed header?

is it just automatic? was interesting in adding a touch more padding, but have a feeling we've been here before..
