### ISSUE TITLE
Pull ToT/dev/beta/stable protocol.json from Blink

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#4]
Lets make sure this doesn't go stale. 

We should also  indicate the blink/chrome version this represents.

So, on every update:
- grab the protocol.json source
- grab date of most recent repo commit, 
- grab the blink & chromium version numbers.

**Comment by paulirish** [comment]
Provide links to look at protocol for stable/beta/canary etc.

**Comment by paulirish** [comment]
I've forked the repo to show a v1.1 protocol viewer: http://chromedevtools.github.io/debugger-protocol-viewer-1.1/

this isn't the most optimal way of handling versions, but it's something.

**Comment by kdzwinel** [comment]
Yep, looks good! Although I'd ❤️ to have everything in one place eventually. I'll give it a shoot in a spare time.

**Comment by TimvdLippe** [comment]
@paulirish I think we did this now, with your auto-update scripts. Shall we close this issue?

**Comment by paulirish** [comment]
We don't show expose what the protocol is in current CHrome stable, but IMO it doesn't seem very neccessary. 

I'm very happy we expose the node.js endpoint. Probably there is where we'd have the most demand to freeze and expose a node8 (or whatever) protocol.

But for now, yeah let's close this.
