### ISSUE TITLE
"DevTools protocol" vs  "Remote Debugging Protocol"

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#40]
Thing called "Chrome DevTools protocol" is deprecated: https://code.google.com/p/chromedevtools/wiki/ChromeDevToolsProtocol

The correct name, according to the old docs, is "Remote Debugging Protocol":
https://developer.chrome.com/devtools/docs/debugger-protocol

In the docs we are using names such as "DevTools protocol" and "Chrome DevTools debugger protocol". IMO we should consider changing that to "Remote Debugging Protocol"

**Comment by paulirish** [comment]
yeah theres inconsistency.

we should just standardize

I'm good with either "Chrome debugging protocol" or "Chrome debugger protocol"

**Comment by auchenberg** [comment]
"Remote debugging protocols" has always had a weird emphasis on "remote control", so I'd +1 for "Chrome debugging protocol"

**Comment by paulirish** [comment]
good call.
