### ISSUE TITLE
Clarification on official protocol name

### ISSUE THREAD

**Issue by auchenberg** [ChromeDevTools/debugger-protocol-viewer#41]
What's the official name for the remote debugging protocol used by Chrome? The variants I've seen a few places:

1. Chrome Debugger Protocol.
2. Chrome Debugging Protocol.
3. Chrome Remote Debugging Protocol.

I'm confused. :confused:

**Comment by paulirish** [comment]
[thx to you](https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/40) we went with "Chrome Debugging Protocol" 

however we didnt' change this repo. i'll do that now. :)

**Comment by paulirish** [comment]
Well, I changed it, but then it broke the site (which doesnt get a redirect).

So I reverted the repo rename for now. 

I'll fix the names on the developer.chrome docs.

**Comment by auchenberg** [comment]
Yeah, I remember that, but when I saw your docs, and when thought you might had changed your mind :)

Roger and thanks! I'll update our docs then.

**Comment by paulirish** [comment]
see also my changes here: https://github.com/GoogleChrome/devtools-docs/commit/c594416107ad1a5754c6f2bafdcbf3ab146a8c61
