### ISSUE TITLE
Review 1.1 view of API

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#45]
Deployed as a separate site for convenience. Would prefer to augment this existing app to support multiple versions, as defined in #4. But hey.

http://chromedevtools.github.io/debugger-protocol-viewer-1.1/
https://github.com/ChromeDevTools/debugger-protocol-viewer/compare/gh-pages-1.1

@kdzwinel happy for you to take a look.

**Comment by auchenberg** [comment]
Any plans on bumping the version anytime soon since this fork is taking place?

**Comment by paulirish** [comment]
@auchenberg bumping which version? 

the protocol is updated... somewhat regularly (i think there may be a bug in my cron job.. )

**Comment by auchenberg** [comment]
@paulirish I was just curious to hear if you had any plans on bumping the protocol version from `1.1`, as it's been quite a while since you bumped the version number. Don't know what the version policy is.

**Comment by kdzwinel** [comment]
@paulirish do we still need this fork (and this issue) for anything?

**Comment by paulirish** [comment]
nope

**Comment by paulirish** [comment]
repo deleted.
