### ISSUE TITLE
Edge Diagnostic Adapter support

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#49]
Since we added support for multiple versions of the protocol, I've been thinking about including [APIs supported by the Edge Diagnostic Adapter](https://github.com/Microsoft/edge-diagnostics-adapter/wiki/Supported-features-and-API). @paulirish is on board with this idea. @auchenberg WDYT?

Only thing that we need to make this happen is a `protocol.json` file describing APIs supported by the Chrome Debugging Protocol endpoint in Edge.

**Comment by auchenberg** [comment]
We provide a [protocol.json[(https://github.com/Microsoft/edge-diagnostics-adapter/blob/f28a16c57fa9c23cd6e4c31ac6b8bab7db31154b/protocol.json) for the Edge Diagnostics Adapter, so this documentation could easily be used to display the supported API of Edge.

However, at Microsoft we want a common, independent protocol, that isn't maintained by one browser vendor, so if `debugger-protocol-viewer` would gain Edge support, I'd like to see it live on a non-browser place like RemoteDebug or somewhere entirely new.

**Comment by paulirish** [comment]
New location: https://github.com/Microsoft/edge-diagnostics-adapter/blob/master/src/chromeProtocol/protocol.json

**Comment by TimvdLippe** [comment]
What is our plan for this issue. Do we still want to do this?

**Comment by paulirish** [comment]
Well I think this is now rendered incomplete by the Edge DevTools protocol (which is different from the diagnostics adapter, but is the Edge longterm plan)

https://docs.microsoft.com/en-us/microsoft-edge/devtools-protocol/
https://docs.microsoft.com/en-us/microsoft-edge/devtools-protocol/0.1/domains/
https://www.youtube.com/watch?v=VhJA2yKp_y8
