### ISSUE TITLE
Establish this as new default protocol doc viewer

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#5]
Related to  #4: "Pull latest protocol.json from Blink"

We could deprecate these pages
- https://developer.chrome.com/devtools/docs/protocol/tot/index this one is definitely useless, especially now.
- https://developer.chrome.com/devtools/docs/protocol/1.1/index
- https://developer.chrome.com/devtools/docs/protocol/1.0/index
- https://developer.chrome.com/devtools/docs/protocol/0.1/index

And use this viewer here for all of them. 
### in repo

The 1.0 and 1.1 protocols are actually in the blink repo so this is easy:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/&q=protocol.json&sq=package:chromium&type=cs (inspector-XX.json)

This is being tracked via this milestone:
https://github.com/ChromeDevTools/debugger-protocol-viewer/milestones/Ship%20as%20the%20new%20default%20viewer

**Comment by kdzwinel** [comment]
https://github.com/GoogleChrome/devtools-docs/commit/1d2e14d27b6a9b824d254c6545022955d31cb7fb - http://chromedevtools.github.io/debugger-protocol-viewer/ mentioned in the DevTools docs.

**Comment by paulirish** [comment]
done, now.
