### ISSUE TITLE
Page.loadEventFired returns unknown timestamp

### ISSUE THREAD

**Issue by GarthDB** [ChromeDevTools/debugger-protocol-viewer#55]
The documentation is lacking on [Page.loadEventFired](https://chromedevtools.github.io/debugger-protocol-viewer/1-1/Page/#event-loadEventFired) it returns a parameter timestamp `number`, but I cannot figure out what this number means. I'm getting numbers like `1894443.789323` which doesn't seem to be a unix epoch timestamp.

**Comment by kdzwinel** [comment]
This repo tracks issues in the protocol viewer, not the viewer itself, so I have to close this issue. However, may I happen to know the problem you are facing. I had hard time figuring out timestamp format myself and I ended up writing this code: https://github.com/kdzwinel/betwixt/blob/master/src/lib/init-time.js . Don't remember the details, but it does work.
