### ISSUE TITLE
Page, Rendering, etc domains missing

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#59]
Discovered today that our tot was missing a few domains.

Found the bug and fixed it.

Over in merge-protocol-files, the `Object.assign` didn't seem to be friendly to arrays.
So it took protocol2's 5 array items and overwrote protocol1's first five array items.

whooops.

**Comment by paulirish** [comment]
Fixed in 0e792113cd7fbb8434d7b78c62cd453a4c2f555e
Updated to use spread operator in 80c513fd335cae95bf8b61246c3a96a1439a359d

And bumped all the files in 26b0d22f07e90eb54f5416693d1d787e33cfc268
You can see the addition of these five domains: `Emulation, Inspector, Memory, Page, Rendering`

**Comment by kdzwinel** [comment]
It's because it copies `length` attribute truncating the result (facepalm). Thank you for fixing it!

**Comment by paulirish** [comment]
All good, amigo.
