### ISSUE TITLE
Update stable devtools protocol to v1.2

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#64]
Talked this over with dgozman and we agree on this basic approach:

* use current day copy of the protocol
* filter out everything that's experimental or deprecated (incl domains)
* ship as 1.2 (stable)
* remove 1.1

**Comment by auchenberg** [comment]
Does this mean `CDP 1.2` has been finalized as of today?

**Comment by paulirish** [comment]
yup
