### ISSUE TITLE
Broken history/scroll support

### ISSUE THREAD

**Issue by cyrus-and** [ChromeDevTools/debugger-protocol-viewer#71]
Despite the URL is properly updated with the correct hash when navigating backward/forward the history, the scroll remains at the top of the page. Not sure if this worked before.

Chrome 54.0.2840.98 on macOS.

**Comment by kdzwinel** [comment]
Yep, confirmed. It's probably a polymer bug though, maybe it's time to update (or ditch polymer and use material design light instead)?

Thanks for reporting!

**Comment by aslushnikov** [comment]
This indeed hurts a lot.

**Comment by cyrus-and** [comment]
I'm not sure if this has been introduced by #85, but now the `content` lies behind the `app-header` thus hiding it.

![2017-10-18-142656_1920x1080_scrot](https://user-images.githubusercontent.com/1660263/31718557-b1e32b1e-b410-11e7-8b9e-53803ef8afcb.png)

*(Transparency added for clarity.)*

**Comment by paulirish** [comment]
@TimvdLippe do you want to take a look at this?

**Comment by TimvdLippe** [comment]
It seems like this is an artifact of `app-header-layout`. I filed an upstream issue at https://github.com/PolymerElements/app-layout/issues/519 to see how we can fix this.
