### ISSUE TITLE
Break on debugger statement without having browser open

### ISSUE THREAD

**Issue by Jbudone** [ChromeDevTools/debugger-protocol-viewer#72]
Currently if you want to hit a debugger; breakpoint you have to have the browser/debugger already open. It would be really cool to break without having the debugger open.

This would be particularly useful in cases where you run test scripts, spawn large number of node processes, or run into an unexpected error. Instead of having to open the browser every time you could simply open it when the debugger statement has been hit

**Comment by kdzwinel** [comment]
Hey! You should probably report that to the Chrome team ( crbug.com ) or Node.js team ( https://github.com/nodejs/node ). Here, we track only issues related to the https://chromedevtools.github.io/debugger-protocol-viewer/ website. Thanks!
