### ISSUE TITLE
Security.SecurityState broken in stable(1.2)

### ISSUE THREAD

**Issue by gcooney** [ChromeDevTools/debugger-protocol-viewer#73]
The spec for network.response in the stable(1.2) build contains the property securityState which links to Security.SecurityState for the property definition.  The domain Security does not exist in 1.2 so this is a dead link.

**Comment by kdzwinel** [comment]
@gcooney thanks for reporting! 

[Link to the section in question.](https://chromedevtools.github.io/debugger-protocol-viewer/1-2/Network/#type-Response). AFAIK there is `Security.CertificateId` and `Security.SecurityState` that are both pointing to the Security domain that does not exist.

@paulirish any Idea how `Security` domain should look in v1.2?

**Comment by kdzwinel** [comment]
Moved to the devtools-protocol repo.
