### ISSUE TITLE
Work offline

### ISSUE THREAD

**Issue by aslushnikov** [ChromeDevTools/debugger-protocol-viewer#79]
It would be nice to support service worker to make protocol viewer available offline.

**Comment by paulirish** [comment]
we do have a service worker, thanks to #91. 

but I guess we don't register it yet. shall we, @TimvdLippe ?

**Comment by TimvdLippe** [comment]
Yes SW seems a good one. I didn't want to enable to in #91 as it was already very large, but we can now more safely test this.
