### ISSUE TITLE
Single-Page application

### ISSUE THREAD

**Issue by aslushnikov** [ChromeDevTools/debugger-protocol-viewer#80]
Oftentimes, navigation to different domains takes a lot of time, especially on a laggy connection. 

Since the whole UI is based on just two `.json` files, we can load descriptors proactively and render different protocol domains instantly, without any network roundtrips.

**Comment by kdzwinel** [comment]
Yeah, this app is getting a bit dated.
<img width="601" alt="screen shot 2017-05-02 at 22 32 15" src="https://cloud.githubusercontent.com/assets/985504/25638011/400dd7ae-2f87-11e7-807d-e04968b72e1a.png">

Originally, it was a "[SPA](https://rawgit.com/ChromeDevTools/devtools-protocol/v0.1/index.html)". I don't remember the reasoning behind making it a normal webpage again. SEO?

Anyway, I'll gladly do it (SPA + SW), just not this month.

**Comment by kensoh** [comment]
I also experience that, thought it is just my Safari browser. It will show a blank page for a while before the content appears. From the chrome-remote-interface project looks like the protocol.json file is 600kb for v1.2.

**Comment by TimvdLippe** [comment]
I can include this as well with the Polymer 2 upgrade and `<app-location>`. Will take a look!

**Comment by paulirish** [comment]
fixed with #91

**Comment by kensoh** [comment]
Blazing fast! Both for clicking navigation menu and clicking search results.
