### ISSUE TITLE
printToPDF DPI problem

### ISSUE THREAD

**Issue by Groarq** [ChromeDevTools/debugger-protocol-viewer#82]
Hello! 

I'm looking for some advice about my problem. 
I've got huge webpage which is in 300DPI and should be 12.5inch x 18.5x. (Its 3750px x 5550px)
By using `Page.printToPDF` I need to set paper size: 39inch x 57.8inch. As I know, there is no option to change DPI property and it's constant.
My only idea was to use scale option, but it lowers quality, slightly breaks some HTML elements and PDF weight stays the same. I think its because of many high resolution images. So my idea seems to be sensless for my case. 

Do you have any workaround or proper solution for such cases?

**Comment by kensoh** [comment]
Hi @Groarq I'm not an expert with the CDP, are the Emulation domain -> setDeviceMetricsOverride method -> deviceScaleFactor and scale properties able to do anything for your use case? https://chromedevtools.github.io/devtools-protocol/1-2/Emulation/

**Comment by TimvdLippe** [comment]
This issue was moved to ChromeDevTools/devtools-protocol#93
