### ISSUE TITLE
Unable to scroll to the bottom of the list of domains

### ISSUE THREAD

**Issue by kdzwinel** [ChromeDevTools/debugger-protocol-viewer#92]
by @gsouf

Hi,

When navigating on the doc hosted on github pages the left menu is not reachable and last items cannot be clicked.

See :

![cdp1](https://user-images.githubusercontent.com/3215399/32942670-03dabb36-cb8a-11e7-859e-fd3115751dfc.PNG)

Expected result:

![cdp2](https://user-images.githubusercontent.com/3215399/32942680-09971628-cb8a-11e7-8597-a1a7c6f555d5.PNG)

**Comment by kdzwinel** [comment]
@TimvdLippe unfortunately, this is still a problem in the new version :( Maybe you'll have an idea what's happening - there are two scroll bars (real one and emulated).

**Comment by gsouf** [comment]
Not sure it can help, but it appears that the scroll bar scrolls correctly but the element has a css rule specifying ``position:fixed; bottom: -120px`` replacing with ``bottom: 0`` is what I did to take the second screenshot.

**Comment by TimvdLippe** [comment]
Hm, it seems that the following selector also works:

```css
#domainContainer {
  height: calc(100vh - 127px);
}
```
Where 127 is the height of the dropdownmenu + toolbar. I will try to find a maintainable solution for this; can work on it tomorrow.

**Comment by TimvdLippe** [comment]
Fixed on https://timvdlippe.github.io/devtools-protocol/

Apparently setting the `height` on a child where the parent has `position: fixed;` computes the `height` of the full viewport. Luckily the fix was easy: put it all in a `div` with `height: 100vh; display: flex;`.
