### ISSUE TITLE
Blank page on Firefox

### ISSUE THREAD

**Issue by paps** [ChromeDevTools/debugger-protocol-viewer#93]
### What steps will reproduce the problem?

1. Open https://chromedevtools.github.io/devtools-protocol/ with Firefox (57.0, Debian)

### What is the expected result?
The documentation shows up.

### What happens instead of that?
A blank page.
In the console, there is `TypeError: this._meta.byKey is not a function`

**Comment by paulirish** [comment]
fixed via the refactor in #91

**Comment by paps** [comment]
Sorry but on https://timvdlippe.github.io/devtools-protocol/ and https://chromedevtools.github.io/devtools-protocol/ I still have `TypeError: this._meta.byKey is not a function` with Firefox.

Do you need more information?
