### ISSUE TITLE
Enabling bundling of the app

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#94]
We're currently not bundling. Doing that would make the load much faster. 

But, as noted in https://github.com/ChromeDevTools/debugger-protocol-viewer/pull/91#discussion_r150413892, it's disabled for now because of an upstream bug.

I believe this is the upstream bug: https://github.com/Polymer/polymer-bundler/issues/611

cc @TimvdLippe

**Comment by TimvdLippe** [comment]
On second thought, we can move all imports into a `index-imports.html`. Then we instruct the bundler to bundle everything into that file and in `index.html` we import this `index-imports.html`. We should be able to maintain our base tag and update it for GitHub to make all the links work.
